services:
  backend:
    volumes:
      - /home/suat/uploads:/app/uploads
  ollama:
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
