services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - "5678:5678"
    volumes:
      - .:/app
    command: >
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678
      -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
